#!/bin/bash

# ============================================================================
# Fix CMake Configuration Template Processing
# ============================================================================

PROJECT_ROOT="$(cd .. && pwd)"  # Assume we're in build/ directory
BUILD_DIR="$(pwd)"

echo "🔧 Fixing CMake configuration template processing..."
echo "📁 Project root: $PROJECT_ROOT"
echo "📁 Build directory: $BUILD_DIR"

# First, let's create the template file with the right variables
cat > "$PROJECT_ROOT/config/wt_config.xml.in" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<server>
    <application-settings location="*">
        <session-timeout>3600</session-timeout>
        <session-id-length>128</session-id-length>
        <debug>false</debug>
        <send-xhtml-mime-type>false</send-xhtml-mime-type>
        <progressive-bootstrap>false</progressive-bootstrap>
        <ajax-puzzle>false</ajax-puzzle>
        
        <properties>
            <property name="theme-base-path">@CMAKE_BINARY_DIR@/assets/css</property>
            <property name="theme-default">restaurant-theme</property>
            <property name="theme-framework-enabled">true</property>
            <property name="bootstrap-enabled">true</property>
            <property name="bootstrap-version">5.3</property>
            <property name="css-loading-strategy">dynamic</property>
            <property name="pos-mode-default">cashier</property>
            <property name="kitchen-display-enabled">true</property>
            <property name="responsive-design">true</property>
        </properties>
    </application-settings>

    <static-resources>
        <static-resource>
            <url>/assets/css</url>
            <path>@CMAKE_BINARY_DIR@/assets/css</path>
            <expires>86400</expires>
        </static-resource>
        
        <static-resource>
            <url>/css/themes</url>
            <path>@CMAKE_BINARY_DIR@/assets/css/themes</path>
            <expires>86400</expires>
        </static-resource>
        
        <static-resource>
            <url>/css/components</url>
            <path>@CMAKE_BINARY_DIR@/assets/css/components</path>
            <expires>86400</expires>
        </static-resource>
        
        <static-resource>
            <url>/js</url>
            <path>@CMAKE_BINARY_DIR@/assets/js</path>
            <expires>86400</expires>
        </static-resource>
    </static-resources>

    <log-config>
        <log-level>info</log-level>
        <log-file>logs/restaurant_pos.log</log-file>
    </log-config>
</server>
EOF

# Now create a CMake snippet to add to CMakeLists.txt
cat > "$BUILD_DIR/cmake_config_addition.txt" << EOF
# Add this to your CMakeLists.txt in the configuration section:

# ============================================================================
# CONFIGURATION FILE PROCESSING - Add this section
# ============================================================================

# Process the configuration template
configure_file(
    "\${CMAKE_SOURCE_DIR}/config/wt_config.xml.in"
    "\${CMAKE_BINARY_DIR}/wt_config.xml"
    @ONLY
)

# Make sure config processing happens before build
add_custom_target(process_config
    DEPENDS "\${CMAKE_BINARY_DIR}/wt_config.xml"
    COMMENT "Processing Wt configuration template"
)

# Make the main executable depend on config processing
add_dependencies(\${PROJECT_NAME} process_config)

# ============================================================================
EOF

echo "✅ CMake template fixed!"
echo ""
echo "📝 To integrate with your CMakeLists.txt:"
echo "   1. Copy the template to config/wt_config.xml.in (done)"
echo "   2. Add the CMake code from: cmake_config_addition.txt"
echo "   3. Or use the working config generated by the other script"
echo ""
echo "🔧 Manual integration:"
echo "   - Open your CMakeLists.txt"
echo "   - Add the configure_file() command shown in cmake_config_addition.txt"
echo "   - This will process @CMAKE_BINARY_DIR@ variables automatically"
echo ""
echo "💡 For immediate use, run the generate_working_config.sh script instead"
echo "   This creates a ready-to-use config without needing CMake changes"
